"""Init

Revision ID: 7c0f3ffcfe0e
Revises: 
Create Date: 2021-04-21 18:32:15.023269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c0f3ffcfe0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mapRegions')
    op.drop_index('ix_jita_sell_order_type_id', table_name='jita_sell_order')
    op.drop_table('jita_sell_order')
    op.drop_index('ix_invTypes_groupID', table_name='invTypes')
    op.drop_table('invTypes')
    op.drop_index('ix_mapSolarSystems_constellationID', table_name='mapSolarSystems')
    op.drop_index('ix_mapSolarSystems_regionID', table_name='mapSolarSystems')
    op.drop_index('ix_mapSolarSystems_security', table_name='mapSolarSystems')
    op.drop_table('mapSolarSystems')
    op.drop_table('invVolumes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invVolumes',
    sa.Column('typeID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('volume', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('typeID'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('mapSolarSystems',
    sa.Column('regionID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('constellationID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('solarSystemID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('solarSystemName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('x', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('y', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('z', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('xMin', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('xMax', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('yMin', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('yMax', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('zMin', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('zMax', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('luminosity', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('border', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('fringe', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('corridor', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('hub', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('international', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('regional', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('constellation', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('security', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('factionID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('radius', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('sunTypeID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('securityClass', mysql.VARCHAR(length=2), nullable=True),
    sa.CheckConstraint('(`border` in (0,1))', name='mapss_border'),
    sa.CheckConstraint('(`constellation` in (0,1))', name='mapss_constel'),
    sa.CheckConstraint('(`corridor` in (0,1))', name='mapss_corridor'),
    sa.CheckConstraint('(`fringe` in (0,1))', name='mapss_fringe'),
    sa.CheckConstraint('(`hub` in (0,1))', name='mapss_hub'),
    sa.CheckConstraint('(`international` in (0,1))', name='mapss_internat'),
    sa.CheckConstraint('(`regional` in (0,1))', name='mapss_regional'),
    sa.PrimaryKeyConstraint('solarSystemID'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_mapSolarSystems_security', 'mapSolarSystems', ['security'], unique=False)
    op.create_index('ix_mapSolarSystems_regionID', 'mapSolarSystems', ['regionID'], unique=False)
    op.create_index('ix_mapSolarSystems_constellationID', 'mapSolarSystems', ['constellationID'], unique=False)
    op.create_table('invTypes',
    sa.Column('typeID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('groupID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('typeName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('mass', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('volume', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('capacity', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('portionSize', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raceID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('basePrice', mysql.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('published', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('marketGroupID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('iconID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('soundID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('graphicID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`published` in (0,1))', name='invtype_published'),
    sa.PrimaryKeyConstraint('typeID'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_invTypes_groupID', 'invTypes', ['groupID'], unique=False)
    op.create_table('jita_sell_order',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_jita_sell_order_type_id', 'jita_sell_order', ['type_id'], unique=False)
    op.create_table('mapRegions',
    sa.Column('regionID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('regionName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('x', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('y', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('z', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('xMin', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('xMax', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('yMin', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('yMax', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('zMin', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('zMax', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('factionID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('radius', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('regionID'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
